name: validate
on: push
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.9'
      - name: Run build
        run: go build ./cmd/generate-builder-opts
      - name: Run test
        run: go test -v ./cmd/generate-builder-opts